version: "3.0"
services:
  limesurvey:
    image: martialblog/limesurvey:6-apache
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_HOST=lime-db"
      - "DB_TYPE=dblib"
      - "DB_PORT=1433"
      - "DB_USERNAME=sa"
      - "DB_PASSWORD=yourStrong(!)Password"
      - "ADMIN_PASSWORD=foobar"
      - "PUBLIC_URL=http://192.168.32.3:8080/"  # Example, Change this
      - "BASE_URL=http://192.168.32.3:8080/"  # Example, Change this
  lime-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
